- id: '1763973069444'
  alias: Rozvrh Přízemí - Michal (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: Přízemí - Michal
      climate_entity: climate.prizemi_michal
      schedule_enable: input_boolean.schedule_enable_prizemi_michal
      last_comfort_helper: input_number.prizemi_michal_last_comfort
      monday_start: input_datetime.prizemi_michal_monday_start
      monday_end: input_datetime.prizemi_michal_monday_end
      tuesday_start: input_datetime.prizemi_michal_tuesday_start
      tuesday_end: input_datetime.prizemi_michal_tuesday_end
      wednesday_start: input_datetime.prizemi_michal_wednesday_start
      wednesday_end: input_datetime.prizemi_michal_wednesday_end
      thursday_start: input_datetime.prizemi_michal_thursday_start
      thursday_end: input_datetime.prizemi_michal_thursday_end
      friday_start: input_datetime.prizemi_michal_friday_start
      friday_end: input_datetime.prizemi_michal_friday_end
      saturday_start: input_datetime.prizemi_michal_saturday_start
      saturday_end: input_datetime.prizemi_michal_saturday_end
      sunday_start: input_datetime.prizemi_michal_sunday_start
      sunday_end: input_datetime.prizemi_michal_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1763973274914'
  alias: Rozvrh 1. patro - Jídelna (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      climate_entity: climate.1p_jidelna
      zone_name: 1. patro - Jídelna
      schedule_enable: input_boolean.schedule_enable_1p_jidelna
      last_comfort_helper: input_number.1p_jidelna_last_comfort
      monday_start: input_datetime.1p_jidelna_monday_start
      monday_end: input_datetime.1p_jidelna_monday_end
      tuesday_start: input_datetime.1p_jidelna_tuesday_start
      tuesday_end: input_datetime.1p_jidelna_tuesday_end
      wednesday_start: input_datetime.1p_jidelna_wednesday_start
      wednesday_end: input_datetime.1p_jidelna_wednesday_end
      thursday_start: input_datetime.1p_jidelna_thursday_start
      thursday_end: input_datetime.1p_jidelna_thursday_end
      friday_start: input_datetime.1p_jidelna_friday_start
      friday_end: input_datetime.1p_jidelna_friday_end
      saturday_start: input_datetime.1p_jidelna_saturday_start
      saturday_end: input_datetime.1p_jidelna_saturday_end
      sunday_start: input_datetime.1p_jidelna_sunday_start
      sunday_end: input_datetime.1p_jidelna_sunday_end
      external_temperature_sensor: sensor.tz3000_jidelna_teplota
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1763973555645'
  alias: Rozvrh 2. patro - Máma (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: 2. patro - Máma
      climate_entity: climate.2p_mama
      schedule_enable: input_boolean.schedule_enable_2p_mama
      last_comfort_helper: input_number.2p_mama_last_comfort
      monday_start: input_datetime.2p_mama_monday_start
      monday_end: input_datetime.2p_mama_monday_end
      tuesday_start: input_datetime.2p_mama_tuesday_start
      tuesday_end: input_datetime.2p_mama_tuesday_end
      wednesday_start: input_datetime.2p_mama_wednesday_start
      wednesday_end: input_datetime.2p_mama_wednesday_end
      thursday_start: input_datetime.2p_mama_thursday_start
      thursday_end: input_datetime.2p_mama_thursday_end
      friday_start: input_datetime.2p_mama_friday_start
      friday_end: input_datetime.2p_mama_friday_end
      saturday_start: input_datetime.2p_mama_saturday_start
      saturday_end: input_datetime.2p_mama_saturday_end
      sunday_start: input_datetime.2p_mama_sunday_start
      sunday_end: input_datetime.2p_mama_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1763997614562'
  alias: Rozvrh 1. patro - Kuchyň (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: '1P Kuchyň '
      climate_entity: climate.1p_kuchyn
      schedule_enable: input_boolean.schedule_enable_1p_kuchyn
      last_comfort_helper: input_number.1p_kuchyn_last_comfort
      monday_start: input_datetime.1p_kuchyn_monday_start
      monday_end: input_datetime.1p_kuchyn_monday_end
      tuesday_start: input_datetime.1p_kuchyn_tuesday_start
      tuesday_end: input_datetime.1p_kuchyn_tuesday_end
      wednesday_start: input_datetime.1p_kuchyn_wednesday_start
      wednesday_end: input_datetime.1p_kuchyn_wednesday_end
      thursday_start: input_datetime.1p_kuchyn_thursday_start
      thursday_end: input_datetime.1p_kuchyn_thursday_end
      friday_start: input_datetime.1p_kuchyn_friday_start
      friday_end: input_datetime.1p_kuchyn_friday_end
      saturday_start: input_datetime.1p_kuchyn_saturday_start
      saturday_end: input_datetime.1p_kuchyn_saturday_end
      sunday_start: input_datetime.1p_kuchyn_sunday_start
      sunday_end: input_datetime.1p_kuchyn_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1764054803049'
  alias: Rozvrh 1. patro - Koupelna (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: 1P Koupelna
      climate_entity: climate.1p_koupelna
      schedule_enable: input_boolean.schedule_enable_1p_koupelna
      last_comfort_helper: input_number.1p_koupelna_last_comfort
      monday_start: input_datetime.1p_koupelna_monday_start
      monday_end: input_datetime.1p_koupelna_monday_end
      tuesday_start: input_datetime.1p_koupelna_tuesday_start
      tuesday_end: input_datetime.1p_koupelna_tuesday_end
      wednesday_start: input_datetime.1p_koupelna_wednesday_start
      wednesday_end: input_datetime.1p_koupelna_wednesday_end
      thursday_start: input_datetime.1p_koupelna_thursday_start
      thursday_end: input_datetime.1p_koupelna_thursday_end
      friday_start: input_datetime.1p_koupelna_friday_start
      friday_end: input_datetime.1p_koupelna_friday_end
      saturday_start: input_datetime.1p_koupelna_saturday_start
      saturday_end: input_datetime.1p_koupelna_saturday_end
      sunday_start: input_datetime.1p_koupelna_sunday_start
      sunday_end: input_datetime.1p_koupelna_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1764055097440'
  alias: Rozvrh 1. patro - Chodba (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: 1P Chodba
      climate_entity: climate.1p_chodba
      schedule_enable: input_boolean.schedule_enable_1p_chodba
      last_comfort_helper: input_number.prizemi_chodba_last_comfort
      monday_start: input_datetime.1p_chodba_monday_start
      monday_end: input_datetime.1p_chodba_monday_end
      tuesday_start: input_datetime.1p_chodba_tuesday_start
      tuesday_end: input_datetime.1p_chodba_tuesday_end
      wednesday_start: input_datetime.1p_chodba_wednesday_start
      wednesday_end: input_datetime.1p_chodba_wednesday_end
      thursday_start: input_datetime.1p_chodba_thursday_start
      thursday_end: input_datetime.1p_chodba_thursday_end
      friday_start: input_datetime.1p_chodba_friday_start
      friday_end: input_datetime.1p_chodba_friday_end
      saturday_start: input_datetime.1p_chodba_saturday_start
      saturday_end: input_datetime.1p_chodba_saturday_end
      sunday_start: input_datetime.1p_chodba_sunday_start
      sunday_end: input_datetime.1p_chodba_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1764055710559'
  alias: Rozvrh Sklep - Michal (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: Sklep Michal
      climate_entity: climate.sklep_michal
      schedule_enable: input_boolean.schedule_enable_sklep_michal
      last_comfort_helper: input_number.sklep_michal_last_comfort
      monday_start: input_datetime.sklep_michal_monday_start
      monday_end: input_datetime.sklep_michal_monday_end
      tuesday_start: input_datetime.sklep_michal_tuesday_start
      tuesday_end: input_datetime.sklep_michal_tuesday_end
      wednesday_start: input_datetime.sklep_michal_wednesday_start
      wednesday_end: input_datetime.sklep_michal_wednesday_end
      thursday_start: input_datetime.sklep_michal_thursday_start
      thursday_end: input_datetime.sklep_michal_thursday_end
      friday_start: input_datetime.sklep_michal_friday_start
      friday_end: input_datetime.sklep_michal_friday_end
      saturday_start: input_datetime.sklep_michal_saturday_start
      saturday_end: input_datetime.sklep_michal_saturday_end
      sunday_start: input_datetime.sklep_michal_sunday_start
      sunday_end: input_datetime.sklep_michal_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1764142337779'
  alias: Rozvrh Přízemí - Chodba záchod (BP)
  description: ''
  use_blueprint:
    path: heating/smart_zone_schedule.yaml
    input:
      zone_name: Přízemí - Chodba záchod
      climate_entity: climate.prizemi_chodba_zachod
      schedule_enable: input_boolean.schedule_enable_prizemi_chodba_zachod
      last_comfort_helper: input_number.prizemi_chodba_zachod_last_comfort
      monday_start: input_datetime.prizemi_chodba_zachod_monday_start
      monday_end: input_datetime.prizemi_chodba_zachod_monday_end
      tuesday_start: input_datetime.prizemi_chodba_zachod_tuesday_start
      tuesday_end: input_datetime.prizemi_chodba_zachod_tuesday_end
      wednesday_start: input_datetime.prizemi_chodba_zachod_wednesday_start
      wednesday_end: input_datetime.prizemi_chodba_zachod_wednesday_end
      thursday_start: input_datetime.prizemi_chodba_zachod_thursday_start
      thursday_end: input_datetime.prizemi_chodba_zachod_thursday_end
      friday_start: input_datetime.prizemi_chodba_zachod_friday_start
      friday_end: input_datetime.prizemi_chodba_zachod_friday_end
      saturday_start: input_datetime.prizemi_chodba_zachod_saturday_start
      saturday_end: input_datetime.prizemi_chodba_zachod_saturday_end
      sunday_start: input_datetime.prizemi_chodba_zachod_sunday_start
      sunday_end: input_datetime.prizemi_chodba_zachod_sunday_end
      eco_temp_default: input_number.eco_temp_default
      boost_active_sensor: binary_sensor.kotel_boost_active
      boost_active: binary_sensor.kotel_boost_active
- id: '1764976713111'
  alias: Externí sensor - 1.P - Jídelna
  description: ''
  use_blueprint:
    path: heating/danfoss_external_sensor.yaml
    input:
      zone_name: 1. patro - Jídelna
      source_temp_sensor: sensor.tz3000_jidelna_teplota
      danfoss_external_temp_number: number.1p_jidelna_senzor_externi_teploty
      danfoss_prefer_external_switch: switch.1p_jidelna_uprednostnit_externi_teplotni_senzor
- id: '1764976820265'
  alias: Externí sensor - Sklep - Michal
  description: ''
  use_blueprint:
    path: heating/danfoss_external_sensor.yaml
    input:
      zone_name: Sklep - Michal
      source_temp_sensor: sensor.mi_air_purifier_2h_teplota
      danfoss_external_temp_number: number.sklep_michal_senzor_externi_teploty
      danfoss_prefer_external_switch: switch.sklep_michal_uprednostnit_externi_teplotni_senzor
